[package]
name = "stanex_tools"
version = "0.1.0"
authors = ["Sanath Govindarajan"]
edition = "2018"

[dependencies]
path_abs = "0.5.0"
clap = "2.33.1"
regex = "1"
lazy_static = "1.4.0"
threadpool = "1.8.1"
