[package]
name = "StanX_tools"
version = "1.0.0"
authors = ["Sanath Govindarajan"]
edition = "2018"

[dependencies]
path_abs = "0.5.1"
clap = "2.33.1"
regex = "1"
lazy_static = "1.4.0"
threadpool = "1.8.1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
anyhow = "1"